### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by lazyeden** [phycholosogy/RAG-privacy#3]
When I evaluated the generated results after running the third step, the following error occurred：
Traceback (most recent call last):
  File "/RAG-privacy/evaluation_results.py", line 767, in <module>
    eval_results(settings, title_table, table_list)
  File "/RAG-privacy/evaluation_results.py", line 603, in eval_results
    sources_, outputs_, contexts_ = get_data(path_, model, tem, p, seq, gen)
  File "/RAG-privacy/evaluation_results.py", line 120, in get_data
    k = len(sources) // len(outputs)
ZeroDivisionError: integer division or modulo by zero

The error occurs in this code. Is there something wrong?:
outputs = output.split('\n===================\n')[:-1]

**Comment by cryingInitial** [comment]
Evaluation not works here too
I tried to solve the problems. But evaluation is virtually impossible

**Comment by Ahram-41** [comment]
It seems because the developer didn't update the evaluation.py file. 
In the commit history of generate.py, information is split by '\n===================\n in txt files, so when running evaluation.py, the splitter cannot split the str into list by '\n===================\n' and zero division error occurs

**Comment by phycholosogy** [comment]
Sorry for late response. I am very sorry for uploading an incorrect file.
In our project, we first using '\n===================\n' to divide different samples, after that we change the 'txt' file into json file, but I forget to update the evaluate file.
I update the "[evaluation_results.py](https://github.com/phycholosogy/RAG-privacy/blob/main/evaluation_results.py)" and test some easy example, it is work now. If you have any questions, please feel free to pull an issue. I'll response soon.
